### ISSUE TITLE
Config: explorer names are not discoverable

### ISSUE THREAD

**Issue by ncw** [negative0/rclone-webui-react#13]
When choosing the backend in the config creator you can no longer see all possible types of backend.

This is great for power users, but I think new users will need discoverable interface so they can see all the backends. 

Ideas?

![image](https://user-images.githubusercontent.com/536803/59192767-6e57d900-8b7b-11e9-818c-29531ed3bc31.png)

**Comment by negative0** [comment]
![DeepinScreenshot_select-area_20190611234243](https://user-images.githubusercontent.com/12236512/59296186-ef5dc000-8ca2-11e9-81d5-24d922f05e2b.png)

**Comment by ncw** [comment]
Perfect :-)
