### ISSUE TITLE
Explorer: store state in the URL

### ISSUE THREAD

**Issue by ncw** [negative0/rclone-webui-react#3]
It would be very nice to store the state of the explorer in the URL.  Currently it is fixed at `http://localhost:3000/#/remoteExplorer` if this was `http://localhost:3000/#/remoteExplorer/drive:/path/dir` then this would make it possible to save the URL and press refresh in the browser.

**Comment by negative0** [comment]
We need to figure out a way to store the current layout and also the remotes and path of all the remote explorers.

**Comment by ncw** [comment]
Using [the syntax that rc uses](https://rclone.org/rc/#rc-serve) would probably work, so `[remote:path]/path/to/object`  if you had multiple panes you could separate them with `|` or something like that.

So `#[remote:path]/path/to/object` or `#[remote:path]/path/to/object|[remote2:path2]/path/to/object`

**Comment by negative0** [comment]
This issue is fixed by using the redux store to store the current state of remote explorer.
