### ISSUE TITLE
Explorer: sort the remotes

### ISSUE THREAD

**Issue by ncw** [negative0/rclone-webui-react#4]
Sorting the remotes would be great in the explorer view.

I have 200 remotes and it is very difficult to find the one I want!

I wonder if a dropdown menu might work better here?

**Comment by negative0** [comment]
Dropdown with auto complete would be actually useful here. Or else we can have a table with search functionality

**Comment by ncw** [comment]
> Dropdown with auto complete would be actually useful here. Or else we can have a table with search functionality

Something where I could type some letters of the remote would be perfect.  I quite like the idea of using less screen real estate too so a dropdown with autocomplete sounds super!
