### ISSUE TITLE
Explorer: local file view

### ISSUE THREAD

**Issue by ncw** [negative0/rclone-webui-react#6]
It is slightly inconvenient to have to make a remote to view local files...

In the explorer remote selection, could we make one which opens a local backend? Or this could be a different button?

Local backends can be specified by path, so "/" will work.  We could get rclone to return the path of the users home directory if we want.  Or maybe we could use a browser choose a directory function - I'm not sure.

So in remote terms you can use `fs="/" remote=""` to view the root directory.

**Comment by negative0** [comment]
We can prompt the user to create a local config if it is not present in the config list. Or we can provide a button to open local config, and upon click, we can ask the user to select a local path, or take "/" as default. Taking "/" might not be convenient for everyone though.

**Comment by ncw** [comment]
> We can prompt the user to create a local config if it is not present in the config list.

That isn't the way rclone is normally used - people don't create local remotes normally, they just use the path directly.

> Or we can provide a button to open local config, and upon click, we can ask the user to select a local path, or take "/" as default. Taking "/" might not be convenient for everyone though.

I was thinking you'd probably want a few options in the list...

So
- / (or C:, D: etc on Windows)
- the users home directory
- the current directory that rclone was started in if different to the above
- the temporary directory (maybe)

I don't know whether you can work these out from the browser - I don't think so.  However it would be trivial to create an api to return a list of interesting local paths.

Asking the user to choose with `/` is the default is not a bad solution to be getting on with.

**Comment by ncw** [comment]
With the new box to type in, could we allow local paths to be typed in there too?  Eg

![image](https://user-images.githubusercontent.com/536803/59192309-f210c600-8b79-11e9-815e-74c69fcb29df.png)

**Comment by negative0** [comment]
It seems like a good idea. But it won't be intuitive.

**Comment by ncw** [comment]
> It seems like a good idea. But it won't be intuitive.

In rclone terms `remote:path` and `/tmp/localdir` are the same things.  `/tmp/localdir` is a special way of writing a local remote with a root of "/tmp/localdir".  So I think that would make sense to existing rclone users.

So you can do

    rclone sync remote:path /tmp/localdir
    rclone sync /tmp/localdir remote:path
    rclone sync /tmp/localdir  /tmp/localdir2
    rclone sync remote:path remote2:path2

And all of those are `rclone sync source_remote destination_remote`

**Comment by jeff15110168** [comment]
Hello - how do i access a local path in the rclone web UI? I'm running the rclone plugin for unraid and accessing via "http://192.168.0.117:5572/#/remoteExplorer"

![image](https://user-images.githubusercontent.com/9892738/170859581-b246ad82-43e1-41d3-97f8-0feed23bc119.png)

**Comment by jeff15110168** [comment]
> Hello - how do i access a local path in the rclone web UI? I'm running the rclone plugin for unraid and accessing via "http://192.168.0.117:5572/#/remoteExplorer"
> 
> ![image](https://user-images.githubusercontent.com/9892738/170859581-b246ad82-43e1-41d3-97f8-0feed23bc119.png)

Bump - can someone help me with this?

**Comment by jeff15110168** [comment]
> Hello - how do i access a local path in the rclone web UI? I'm running the rclone plugin for unraid and accessing via "http://192.168.0.117:5572/#/remoteExplorer"
> 
> ![image](https://user-images.githubusercontent.com/9892738/170859581-b246ad82-43e1-41d3-97f8-0feed23bc119.png)

Bump - can someone help me with this?

**Comment by jeff15110168** [comment]
> Hello - how do i access a local path in the rclone web UI? I'm running the rclone plugin for unraid and accessing via "http://192.168.0.117:5572/#/remoteExplorer"

Bump - can someone help me with this?

**Comment by veneamin** [comment]
> > Hello - how do i access a local path in the rclone web UI? I'm running the rclone plugin for unraid and accessing via "http://192.168.0.117:5572/#/remoteExplorer"
> 
> Bump - can someone help me with this?

if you create local "remote" in config like c:\ = hd1:  you can open hd1: in web and get access to local files. Is it what you need?
