### ISSUE TITLE
Bucket based remotes

### ISSUE THREAD

**Issue by ncw** [negative0/rclone-webui-react#7]
There is a problem with bucket based remotes.

Let's say you have a bucket based remote (s3, swift, gcs, azureblob, etc) called `bbr:` (bucket based remote).

`operations/list fs="bbr:" remote=""` will work fine, listing the buckets, however `operations/list fs="bbr:" remote="bucket"` will **not** work, you'll get this error

    2019/06/07 10:07:15 ERROR : bucket: error listing: bucket or container name is needed in remote

So if you want that to work you need to use `operations/list fs="bbr:bucket" path="" `

I'm not 100% sure you can tell whether a remote is bucket based or not via the API, though it would be easy to add this in.

Possible solutions
1. I change rclone so that `operations/list fs=bbr: path="bucket"` does work
    - Doing this in the backends themselves would be a lot of work
    - Perhaps easier might be to make a wrapping backend which deals with making the subremotes `bbr:bucket` but presenting them as part of `bbr:` and re-writing the paths
2. I change rclone so that `fs=bbr: path="bucket/path" ` gets re-written to `fs=bbr:bucket path="path"` in the API
    - I did try this and it works.  However it is somewhat unexpected since the objects then have the wrong path, so instead of having the path "bucket/path/object" they have the path "path/object".  Which meant that when I tried it with the webui you could open the buckets but none of the objects were copyable etc.  As long as the webgui knew this was happening it would be fixable
3. the webui knows which remotes are bucket based and adapts accordingly

Have you any other ideas?

**Comment by ncw** [comment]
PS if you want to set up a bucket based remote then you can install minio very easily

Here is how I do it in the integration tests

```
minio_dir=/tmp/minio

killall -q minio || true
rm -rf ${minio_dir}
mkdir -p ${minio_dir}
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=secretkey
for i in 1 2 3 4 5; do GO111MODULE=on go get github.com/minio/minio@latest command && break || sleep 2; done
minio server --address 127.0.0.1:9000 ${minio_dir} >/tmp/minio.log 2>&1 &
minio_pid=$!
```

**Comment by negative0** [comment]
It will be trivial to handle this in the WebUI once it knows that it is dealing with a bucket. But we will have to query for the remote config params every time to check for the type of remote as the WebUI is stateless.

It might be dangerous to pass rclone config params every time, what do you think?

One thing that comes to mind, is to add a new parameter, IsBucket like we have IsDirectory.

**Comment by ncw** [comment]
> It will be trivial to handle this in the WebUI once it knows that it is dealing with a bucket. But we will have to query for the remote config params every time to check for the type of remote as the WebUI is stateless.
> 
> It might be dangerous to pass rclone config params every time, what do you think?

I agree with you.

We could make a separate API to ask "is this a bucket based remote"?  In fact there are several useful things that could be queried there so I'd quite like to make that API. It could be used to query the [features](https://rclone.org/overview/#features) and the [optional features](https://rclone.org/overview/#optional-features) of an existing remote.


> One thing that comes to mind, is to add a new parameter, IsBucket like we have IsDirectory.

So in `operations/list` if you listed `bbr:` you'd get back directories with the `IsBucket` flag set to true?  I like that idea and it would be quite simple to implement. Would that be easy to use from the webui?

**Comment by negative0** [comment]
> So in operations/list if you listed bbr: you'd get back directories with the IsBucket flag set to true? I like that idea and it would be quite simple to implement. Would that be easy to use from the webui?

It will be pretty easy to just treat the current object as a bucket, than a directory. It will also be more intuitive that way.

**Comment by negative0** [comment]
> We could make a separate API to ask "is this a bucket based remote"? In fact there are several useful things that could be queried there so I'd quite like to make that API. It could be used to query the features and the optional features of an existing remote.

You are right. This will be required to enable or disable certain functionalities in the webui, it will also make it very easy to implement certain features in the future.

**Comment by negative0** [comment]
I think we should do both. The first one ensures that buckets can be distinguished from directories and the second one can be used for other features

**Comment by ncw** [comment]
I added the `IsBucket` field here

https://beta.rclone.org/branch/v1.47.0-103-g1aa65d60-rc-isbucket-beta/ (uploaded in 15-30 mins)

It was only a few lines of code so I think that is a good solution!  Let me know if it works for you!

**Comment by ncw** [comment]
I've merged the IsBucket to master now and also an `operations/fsinfo` to return info about the remote

Path:  "operations/fsinfo",
Title: "Return information about the remote",

This takes the following parameters

- fs - a remote name string eg "drive:"

This returns info about the remote passed in;

```
{
	// optional features and whether they are available or not
	"Features": {
		"About": true,
		"BucketBased": false,
		"CanHaveEmptyDirectories": true,
		"CaseInsensitive": false,
		"ChangeNotify": false,
		"CleanUp": false,
		"Copy": false,
		"DirCacheFlush": false,
		"DirMove": true,
		"DuplicateFiles": false,
		"GetTier": false,
		"ListR": false,
		"MergeDirs": false,
		"Move": true,
		"OpenWriterAt": true,
		"PublicLink": false,
		"Purge": true,
		"PutStream": true,
		"PutUnchecked": false,
		"ReadMimeType": false,
		"ServerSideAcrossConfigs": false,
		"SetTier": false,
		"SetWrapper": false,
		"UnWrap": false,
		"WrapFs": false,
		"WriteMimeType": false
	},
	// Names of hashes available
	"Hashes": [
		"MD5",
		"SHA-1",
		"DropboxHash",
		"QuickXorHash"
	],
	"Name": "local",	// Name as created
	"Precision": 1,		// Precision of timestamps in ns
	"Root": "/",		// Path as created
	"String": "Local file system at /" // how the remote will appear in logs
}
```

This command does not have a command line equivalent so use this instead:

    rclone rc --loopback operations/fsinfo fs=remote:

**Comment by negative0** [comment]
@ncw I am moving the task of selectively disabling features to a new issue. As it is not directly related to bucket based remotes.
